services:
  router:
    build:
      context: ./src/host_img
    container_name: router
    hostname: router
    networks:
      malcolm_net:
        ipv4_address: 172.23.0.2

  victim:
    build:
      context: ./src/host_img
    container_name: victim
    hostname: victim
    networks:
      malcolm_net:
        ipv4_address: 172.23.0.3

  malcolm:
    build:
      context: ./src/host_img
    container_name: malcolm
    hostname: malcolm
    networks:
      malcolm_net:
        ipv4_address: 172.23.0.4
    volumes:
      - ./src/ft_malcolm:/project

networks:
  malcolm_net:
    name: malcolm_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1
