services:
  router:
    build:
      context: ./src/host_img
    container_name: router
    hostname: router
    networks:
      malcolm_net:
        ipv4_address: ${ROUTER_IP}

  victim:
    build:
      context: ./src/host_img
    container_name: victim
    hostname: victim
    networks:
      malcolm_net:
        ipv4_address: ${VICTIM_IP}

  malcolm:
    build:
      context: ./src/host_img
    container_name: malcolm
    hostname: malcolm
    networks:
      malcolm_net:
        ipv4_address: ${MALCOLM_IP}
    volumes:
      - ./src/ft_malcolm:/project
    env_file:
      - .env

networks:
  malcolm_net:
    name: malcolm_net
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}
